# Thai Energy Trading System Configuration
# Main application configuration for Docker deployment

[database]
host = "postgres"
port = 5432
database = "thai_energy_trading"
username = "thai_energy"
password = "password123"

[redis]
host = "redis"
port = 6379

[server]
host = "0.0.0.0"
port = 8080
websocket_port = 9944
p2p_port = 30333

[logging]
level = "info"
output = "/app/logs/thai-energy-trading.log"

[security]
jwt_secret = "your-jwt-secret-here"
grid_operator_key = "your-grid-operator-key-here"

[energy_trading]
# Energy trading specific configurations
grid_fee_percentage = 0.01
max_order_size = 1000000
min_order_size = 1
order_expiry_minutes = 1440  # 24 hours

[performance]
max_concurrent_requests = 1000
cache_ttl_seconds = 300
batch_size = 100
