apiVersion: v1
kind: Namespace
metadata:
  name: thai-energy-trading
  labels:
    name: thai-energy-trading
    environment: production
    project: thai-energy-trading-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thai-energy-config
  namespace: thai-energy-trading
  labels:
    app: thai-energy-trading
    component: config
data:
  config.toml: |
    # Thai Energy Trading System Configuration
    
    # Network Configuration
    [network]
    listen_addr = "0.0.0.0:30333"
    public_addr = "127.0.0.1:30333"
    node_key_file = "/app/data/node.key"
    chain_spec_path = "/app/config/thai_energy_chain_spec.json"
    
    # API Configuration
    [api]
    http_addr = "0.0.0.0:8080"
    ws_addr = "0.0.0.0:9944"
    cors_origins = ["*"]
    max_connections = 1000
    
    # Database Configuration
    [database]
    path = "/app/data/db"
    cache_size = "1GB"
    pruning = "archive"
    
    # Consensus Configuration
    [consensus]
    algorithm = "aura"
    block_time = 6000  # 6 seconds in milliseconds
    finality_grandpa = true
    
    # Energy Trading Configuration
    [energy_trading]
    grid_fee_rate = 0.01  # 1%
    min_trade_amount = 0.1  # kWh
    max_trade_amount = 10000.0  # kWh
    order_expiry = 86400  # 24 hours in seconds
    
    # Token System Configuration
    [token_system]
    native_token = "GRID"
    stablecoin = "WATT"
    min_stake_amount = 10000
    governance_voting_period = 604800  # 7 days
    
    # Logging Configuration
    [logging]
    level = "info"
    file_path = "/app/logs/thai_energy.log"
    max_file_size = "100MB"
    max_files = 10
    format = "json"
    
    # Telemetry Configuration
    [telemetry]
    enabled = true
    url = "wss://telemetry.polkadot.io/submit/"
    verbosity = 0
    
    # Oracle Configuration
    [oracle]
    enabled = true
    providers = [
        "weather_api",
        "grid_data_api", 
        "market_price_api"
    ]
    update_interval = 60  # seconds
    
    # Security Configuration
    [security]
    max_peers = 50
    reserved_nodes = []
    bootnodes = []

  thai_energy_chain_spec.json: |
    {
      "name": "Thai Energy Trading Chain",
      "id": "thai_energy",
      "chainType": "Local",
      "bootNodes": [],
      "telemetryEndpoints": null,
      "protocolId": "thai_energy",
      "properties": {
        "tokenDecimals": 18,
        "tokenSymbol": "GRID",
        "ss58Format": 42
      },
      "forkId": null,
      "codeSubstitutes": {},
      "genesis": {
        "runtime": {
          "system": {
            "code": "0x"
          },
          "balances": {
            "balances": [
              ["5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY", 1000000000000000000000],
              ["5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty", 1000000000000000000000],
              ["5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y", 1000000000000000000000]
            ]
          },
          "aura": {
            "authorities": [
              "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
              "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
              "5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y"
            ]
          },
          "grandpa": {
            "authorities": [
              ["5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY", 1],
              ["5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty", 1],
              ["5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y", 1]
            ]
          },
          "energyTrading": {
            "gridFeeRate": 1,
            "minTradeAmount": 100,
            "maxTradeAmount": 10000000,
            "authorizedTraders": [
              "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
              "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
              "5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y"
            ]
          },
          "tokenSystem": {
            "nativeToken": "GRID",
            "stablecoin": "WATT",
            "initialSupply": 1000000000000000000000000,
            "governanceTokenHolders": [
              ["5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY", 100000000000000000000000],
              ["5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty", 100000000000000000000000],
              ["5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y", 100000000000000000000000]
            ]
          }
        }
      }
    }
